export const ROOT_STACK = {
  MAIN_APP: 'MAIN_APP',
  GLOBAL_ALERT: 'GLOBAL_ALERT',
  GLOBAL_CONFIRM: 'GLOBAL_CONFIRM',
}

export const SCREEN_ROUTER = {
  MAIN: 'MAIN',
  AUTH: 'AUTH',
  SPLASH: 'SPLASH',
}

export const MAIN_TAB = {
  HOME: 'HOME',
  WORK: 'WORK',
  ACCOUNT: 'ACCOUNT',
}

export const SCREEN_ROUTER_AUTH = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  WELLCOME: 'WELLCOME',
}

export const SCREEN_ROUTER_APP = {
  HOME: 'HOME',
  WORK: 'WORK',
  TEST: 'TEST',
  UPDATE_INFO: 'UPDATE_INFO',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  GARDEN_INFO: 'GARDEN_INFO',
  GARDEN_STAFF: 'GARDEN_STAFF',
  CROP_INFO: 'CROP_INFO',
  WORK_DETAILS: 'WORK_DETAILS',
}
