const images = {
  ic_home: require('./images/ic_home.png'),
  ic_work: require('./images/ic_work.png'),
  ic_account: require('./images/ic_account.png'),
  logo: require('./images/logo.png'),
  ic_eye_hide: require('./images/ic_eye_hide.png'),
  ic_eye_show: require('./images/ic_eye_show.png'),
  ic_fb: require('./images/ic_fb.png'),
  ic_google: require('./images/ic_google.png'),
  ic_apple: require('./images/ic_apple.png'),
  ic_back: require('./images/ic_back.png'),
  lottieLoading: require('./images/loading.json'),
  loadData: require('./images/loadData.json'),
  wellcome1: require('./images/wellcome1.json'),
  wellcome2: require('./images/wellcome2.json'),
  wellcome3: require('./images/wellcome3.json'),
  ic_logout: require('./images/ic_logout.png'),
  ic_tree: require('./images/ic_tree.png'),
  img_wellcome: require('./images/img_wellcome.png'),
  ic_arrow_go: require('./images/ic_arrow_go.png'),
  ic_lock: require('./images/ic_lock.png'),
  ic_user_check: require('./images/ic_user_check.png'),
  ic_info_circle: require('./images/ic_info_circle.png'),
  ic_camera: require('./images/ic_camera.png'),
  ic_calendar: require('./images/ic_calendar.png'),
  ic_check: require('./images/ic_check.png'),
  ic_phone: require('./images/ic_phone.png'),
  ic_search: require('./images/ic_search.png'),
  ic_chat: require('./images/ic_chat.png'),
  img_logout: require('./images/img_logout.png'),
  ic_bell: require('./images/ic_bell.png'),
  // ic_male: require('./images/ic_male.png'),
  // ic_female: require('./images/ic_female.png'),
}
export default images
