const images = {
  ic_home: require('./images/ic_home.png'),
  ic_work: require('./images/ic_work.png'),
  ic_account: require('./images/ic_account.png'),
  logo: require('./images/logo.png'),
  ic_eye_hide: require('./images/ic_eye_hide.png'),
  ic_eye_show: require('./images/ic_eye_show.png'),
  ic_fb: require('./images/ic_fb.png'),
  ic_google: require('./images/ic_google.png'),
  ic_apple: require('./images/ic_apple.png'),
  ic_back: require('./images/ic_back.png'),
  lottieLoading: require('./images/loading.json'),
  loadData: require('./images/loadData.json'),
  wellcome1: require('./images/wellcome1.json'),
  wellcome2: require('./images/wellcome2.json'),
  wellcome3: require('./images/wellcome3.json'),
  ic_logout: require('./images/ic_logout.png'),
  ic_tree: require('./images/ic_tree.png'),
  img_wellcome: require('./images/img_wellcome.png'),
  ic_arrow_go: require('./images/ic_arrow_go.png'),
  ic_lock: require('./images/ic_lock.png'),
  ic_user_check: require('./images/ic_user_check.png'),
  ic_info_circle: require('./images/ic_info_circle.png'),
  ic_camera: require('./images/ic_camera.png'),
  ic_calendar: require('./images/ic_calendar.png'),
  ic_check: require('./images/ic_check.png'),
  ic_phone: require('./images/ic_phone.png'),
  ic_search: require('./images/ic_search.png'),
  ic_chat: require('./images/ic_chat.png'),
  img_logout: require('./images/img_logout.png'),
  ic_bell: require('./images/ic_bell.png'),
  ic_full_screen: require('./images/ic_full_screen.png'),
  ic_muted: require('./images/ic_muted.png'),
  ic_play: require('./images/ic_play.png'),
  ic_pause: require('./images/ic_pause.png'),
  ic_volume: require('./images/ic_volume.png'),
  ic_harvest: require('./images/ic_harvest.png'),
  ic_more: require('./images/ic_more.png'),
  ic_share: require('./images/ic_share.png'),
  ic_heart: require('./images/ic_heart.png'),
  ic_heart_bold: require('./images/ic_heart_bold.png'),
  ic_zoom_out: require('./images/ic_zoom_out.png'),
  ic_enlarge: require('./images/ic_enlarge.png'),
  ic_headPhone: require('./images/ic_headPhone.png'),
  qrScan: require('./images/qrScan.json'),
  ic_map: require('./images/ic_map.png'),
  // ic_male: require('./images/ic_male.png'),
  // ic_female: require('./images/ic_female.png'),
}
export default images
