import i18n from '../i18n/i18n'

function strings() {
  return {
    home: i18n.t('home'),
    work: i18n.t('work'),
    account: i18n.t('account'),
    noti: i18n.t('noti'),
    require_login_message: i18n.t('require_login_message'),
    confirm: i18n.t('confirm'),
    cancel: i18n.t('cancel'),
    login: i18n.t('login'),
    register: i18n.t('register'),
    forgot_password: i18n.t('forgot_password'),
    pleaseLogin: i18n.t('pleaseLogin'),
    username: i18n.t('username'),
    password: i18n.t('password'),
    enter_username: i18n.t('enter_username'),
    enter_password: i18n.t('enter_password'),
    or: i18n.t('or'),
    no_account: i18n.t('no_account'),
    have_account: i18n.t('have_account'),
    please_try_again: i18n.t('please_try_again'),
    login_success: i18n.t('login_success'),
    yes: i18n.t('yes'),
    loading_progress: i18n.t('loading_progress'),
    login_faile: i18n.t('login_faile'),
    register_success: i18n.t('register_success'),
    register_account: i18n.t('register_account'),
    confirm_password: i18n.t('confirm_password'),
    email: i18n.t('email'),
    enter_email: i18n.t('enter_email'),
    email_invalid: i18n.t('email_invalid'),
    email_required: i18n.t('email_required'),
    email_already_in_use: i18n.t('email_already_in_use'),
    password_min_six_character: i18n.t('password_min_six_character'),
    password_required: i18n.t('password_required'),
    password_not_match: i18n.t('password_not_match'),
    you_want_logout: i18n.t('you_want_logout'),
    update_info: i18n.t('update_info'),
    update: i18n.t('update'),
    full_name: i18n.t('full_name'),
    enter_full_name: i18n.t('enter_full_name'),
    phone_number: i18n.t('phone_number'),
    enter_phone_number: i18n.t('enter_phone_number'),
    birtday: i18n.t('birtday'),
    enter_birtday: i18n.t('enter_birtday'),
    address: i18n.t('address'),
    enter_address: i18n.t('enter_address'),
    male: i18n.t('male'),
    female: i18n.t('female'),
    gender: i18n.t('gender'),
  }
}

export default strings
